### ISSUE TITLE
fetching array of objects with arrays

### ISSUE THREAD

**Issue by megselayne** [megselayne/UpReads#8]
I have an array with an object for every public book shelf. Within each object, there is an array attached to the key `google_book_id`. I need to make a fetch for each book id and ideally store it on the original shelf object so as to retain the shelf title key value pair needed on the front end.

I've tried to replicated a Promise.all within the second map, but I'm getting an error that `el.json()` is not a function.

I've been unsuccessful in google results for fetching array of arrays etc.

Lines 39-59 in `bookHelpers.js` under `getPublicBooks`  are the related lines to this issue.

**Comment by megselayne** [comment]
Output of getPublicShelfBooks() on Shelves model (db):
NOTE these are random google book ids for testing
```
[
  { shelf_name: 'Black Lives Matter', id: 1, google_book_id: 'FylCUanlGhAC' },
  { shelf_name: 'Black Lives Matter', id: 1, google_book_id: 'p7uGzQEACAAJ' },
  { shelf_name: 'Black Lives Matter', id: 1, google_book_id: 'ltClDwAAQBAJ' },
  {
    shelf_name: 'Black Women Authors, Fiction',
    id: 2,
    google_book_id: 'MWB3AgAAQBAJ'
  },
  {
    shelf_name: 'Black Women Authors, Fiction',
    id: 2,
    google_book_id: '5GbdTc9OJ78C'
  }
]
```
Output after shelf reducer. (this piece works as expected):
```
[
  {
    shelf_name: 'Black Lives Matter',
    id: 1,
    google_book_ids: [ 'FylCUanlGhAC', 'p7uGzQEACAAJ', 'ltClDwAAQBAJ' ]
  },
  {
    shelf_name: 'Black Women Authors, Fiction',
    id: 2,
    google_book_ids: [ 'MWB3AgAAQBAJ', '5GbdTc9OJ78C' ]
  }
]
```
Desired output from getPublicBooks (this is where I'm stuck):
- should be an array with one array for each book shelf, filled with an object for each book on the shelf. This should allow for easy handling on the FE.
```
[
  [{'a fetched book here from the same shelf'}, {'a fetched book here from the same shelf'},{'a fetched book here from the same shelf'}],
  [{'a fetched book here from the same shelf'}, {'a fetched book here from the same shelf'},{'a fetched book here from the same shelf'}]
]
```

**Comment by jlr7245** [comment]
i do wonder whether it would be a good idea to store title/author of each book in your DB so you don't have to get the information from the API every time? but, i would guess that this SHOULD work:

```js

const shelf = [
  {
    shelf_name: "Black Lives Matter",
    id: 1,
    google_book_ids: ["FylCUanlGhAC", "p7uGzQEACAAJ", "ltClDwAAQBAJ"],
  },
  {
    shelf_name: "Black Women Authors, Fiction",
    id: 2,
    google_book_ids: ["MWB3AgAAQBAJ", "5GbdTc9OJ78C"],
  },
];

Promise.all(
  shelf.map((shelf) =>
    Promise.all(shelf.google_book_ids.map((id) => fetch(id))).then((res) =>
      Promise.all(res.map((book) => book.json()))
    )
  )
).then((results) => console.log(results));

```

you're returning a list of promises from `shelf.map`, and then a list of promises from mapping into fetches. and then last but not least you have to wrap the response in Promise.all and map over each one to get its individual json.

**Comment by megselayne** [comment]
@jlr7245 I certainly wanted to store more data, but google is very restrictive in their documentation about not creating dbs from their API :/

**Comment by megselayne** [comment]
I'll test this out - thank you!

**Comment by megselayne** [comment]
per Google:
"
Unless expressly permitted by the content owner or by applicable law, you will not, and will not permit your end users or others acting on your behalf to, do the following with content returned from the APIs:

Scrape, build databases, or otherwise create permanent copies of such content, or keep cached copies longer than permitted by the cache header;

"

**Comment by megselayne** [comment]
- resolved
